spring:
  data:
    mongodb:
      uri: mongodb+srv://Naveen45:N.naveen%40123@cluster0.zbkvy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: msrattings

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka